[package]
name = "sigma_tcp_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.11"
get_if_addrs = "0.5"
async-trait = "0.1"
